### ISSUE TITLE
cannot create account on MM

### ISSUE THREAD

**Issue by marothe** [johannesfritsch/moneymoney-solana#1]
hi! trying to add this to MM gives me the following error:

17:22:18  Starting account setup assistant.
17:22:23  Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension Solana.lua version 0.10.
          Protocol version: Web Scraping
          Web Banking account: Solana (Crypto Asset Solana)
          Lade Wertpapierbestand für Solana ...
          Sending: GET https://min-api.cryptocompare.com/data/price?fsym=SOL&tsyms=EUR,USD
17:22:24  Received: {"EUR":178.07,"USD":193.64}
          Sending: POST https://api.mainnet-beta.solana.com
          Der API-Server Ihrer Bank antwortet mit der Fehlermeldung: »Forbidden«  Bitte versuchen Sie es später noch einmal oder wenden Sie sich mit dieser Fehlermeldung an den Support Ihrer Bank.

Any ideas?

**Comment by florentinw** [comment]
I've the exact same issue

**Comment by marothe** [comment]
@florentinw made a PR here, I changed the API call back then to retrieve the correct solana balance as the old URL was dead. 

https://github.com/johannesfritsch/moneymoney-solana/pull/2
